### ISSUE TITLE
Where to download bert_pretrained weights from?

### ISSUE THREAD

**Issue by waleed-27** [Elfenreigen/UniChest#1]
Hello! I appreciate your decision to share your source code with the community. Could you kindly include instructions for obtaining the bert_pretrained weights? Additionally, it would be helpful if you could provide a requirements.txt or yml file for setting up a Conda environment. Thank you in advance for your assistance.

**Comment by Elfenreigen** [comment]
We will update our repo and upload corresponding training/testing splitting files, and configuration setting files in next month. Stay tuned!

**Comment by Elfenreigen** [comment]
Details of bert_pretrained please refer to https://github.com/xiaoman-zhang/KAD.
