### ISSUE TITLE
Where to download files mentioned in 'config.yaml'?

### ISSUE THREAD

**Issue by Farzeen-Khalid** [Elfenreigen/UniChest#2]
Hello! I appreciate your decision to share your source code with the community. Could you kindly include instructions for obtaining the following files mentioned in ./config/config.yaml :
1. train_entity_file: './A1_DATA/radgraph_umls.json'
2. train_fg_query_file_v1: './train_all_merge.csv'
3. mrsty_file: './A1_DATA/MRSTY.csv'
4. chestxray_train_file: './A1_DATA/ChestXray14/binary_train.csv'
5. chestxray_valid_file: './A1_DATA/ChestXray14/binary_valid.csv'
6. chestxray_test_file: './A1_DATA/ChestXray14/official_test.csv'
7. padchest_all_test_file: './A1_DATA/Physician_label193_lr.csv'

We have looked in the official repositories but did not find files of these names or nature. Please specify where to download these from or share a pre-processing file which were used to obtain these. Thank you in advance for your assistance.

**Comment by Elfenreigen** [comment]
We will update our repo and upload corresponding training/testing splitting files, and configuration setting files in next month. Stay tuned!
